export const GAME_DATA = [
    { name: 'Chidiya', icon: '🐦', type: 'fly', lang: 'Bird' },
    { name: 'Tota', icon: '🦜', type: 'fly', lang: 'Parrot' },
    { name: 'Maina', icon: '🐧', type: 'fly', lang: 'Myna' },
    { name: 'Kabootar', icon: '🕊️', type: 'fly', lang: 'Pigeon' },
    { name: 'Cheel', icon: '🦅', type: 'fly', lang: 'Eagle' },
    { name: 'Kauwa', icon: '🐦‍⬛', type: 'fly', lang: 'Crow' },
    { name: 'Makkhi', icon: '🪰', type: 'fly', lang: 'Fly' },
    { name: 'Machchar', icon: '🦟', type: 'fly', lang: 'Mosquito' },
    { name: 'Titli', icon: '🦋', type: 'fly', lang: 'Butterfly' },
    { name: 'Vimaan', icon: '✈️', type: 'fly', lang: 'Airplane' },
    { name: 'Rocket', icon: '🚀', type: 'fly', lang: 'Rocket' },
    { name: 'Helicopter', icon: '🚁', type: 'fly', lang: 'Helicopter' },
    
    { name: 'Haathi', icon: '🐘', type: 'ground', lang: 'Elephant' },
    { name: 'Ghoda', icon: '🐎', type: 'ground', lang: 'Horse' },
    { name: 'Sher', icon: '🦁', type: 'ground', lang: 'Lion' },
    { name: 'Kutta', icon: '🐕', type: 'ground', lang: 'Dog' },
    { name: 'Billi', icon: '🐈', type: 'ground', lang: 'Cat' },
    { name: 'Chuha', icon: '🐀', type: 'ground', lang: 'Rat' },
    { name: 'Gaay', icon: '🐄', type: 'ground', lang: 'Cow' },
    { name: 'Bhains', icon: '🐃', type: 'ground', lang: 'Buffalo' },
    { name: 'Kursi', icon: '🪑', type: 'ground', lang: 'Chair' },
    { name: 'Mez', icon: '🪵', type: 'ground', lang: 'Table' },
    { name: 'Car', icon: '🚗', type: 'ground', lang: 'Car' },
    { name: 'Bus', icon: '🚌', type: 'ground', lang: 'Bus' },
    { name: 'Train', icon: '🚂', type: 'ground', lang: 'Train' },
    { name: 'Patthar', icon: '🪨', type: 'ground', lang: 'Stone' },
    { name: 'Insaan', icon: '🚶', type: 'ground', lang: 'Human' }
];
